fix: qbittorrent workflow

diff --git a/.github/workflows/qbittorrent.yml b/.github/workflows/qbittorrent.yml
--- a/.github/workflows/qbittorrent.yml
+++ b/.github/workflows/qbittorrent.yml
@@ -305,6 +305,7 @@ jobs:
             }" > "${tmp_dir}/${package_name_with_suffix}.json"
           echo "Uploading artifact for ${package_name_with_suffix}"
           mkdir -p "${artifacts_dir}/${package_name_with_suffix}"
+          tar -czf "${artifacts_dir}/qt-6.5.2.tar.gz" -C "${QT_ROOT_DIR}" . || echo "Failed to create qt-6.5.2.tar.gz"
           cp "${tmp_dir}/${package_name_with_suffix}.json" "${artifacts_dir}/${package_name_with_suffix}/"
           cp "${pool_path}/${PACKAGE_FILE}" "${artifacts_dir}/${package_name_with_suffix}/"
           ls -al "${artifacts_dir}/${package_name_with_suffix}/"
@@ -411,6 +412,11 @@ jobs:
           fetch-depth: 0
           path: ${{ github.workspace }}/binaries
 
+      - name: Download Package Data Artifacts
+        uses: actions/download-artifact@v4
+        with:
+          path: ${{ github.workspace }}/outputs
+          
       - name: Extract Package Data Artifacts
         run: |
           set -e
